// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmoq_Oam_fclWA4byLFpN5Wj5LYsd6-eE',
    appId: '1:208133681681:web:94b524daf2d0085ffaf7b0',
    messagingSenderId: '208133681681',
    projectId: 'fir-authentication-task-ae864',
    authDomain: 'fir-authentication-task-ae864.firebaseapp.com',
    storageBucket: 'fir-authentication-task-ae864.appspot.com',
    measurementId: 'G-Q0WZ8GSSVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIjsUzKsqRpmnqeem76dVzGz1kf9cl7xM',
    appId: '1:208133681681:android:ccf9df65aa6df027faf7b0',
    messagingSenderId: '208133681681',
    projectId: 'fir-authentication-task-ae864',
    storageBucket: 'fir-authentication-task-ae864.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBneh44fnScy3_2fkvtxHMJihZRuP-r8CA',
    appId: '1:208133681681:ios:32517f818f3507a8faf7b0',
    messagingSenderId: '208133681681',
    projectId: 'fir-authentication-task-ae864',
    storageBucket: 'fir-authentication-task-ae864.appspot.com',
    iosClientId: '208133681681-o9t59m29igh8i9f6hbo6k6krtq8b18u7.apps.googleusercontent.com',
    iosBundleId: 'com.appfirebasetask.firebaseAuthenticationTask',
  );
}
